//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Ingrese un precio válido")]
        [Display(Name = "Precio")]
        public Nullable<double> precio { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Seleccione proveedor")]
        [Display(Name = "Proveedor")]
        public Nullable<int> id_proveedor { get; set; }
        public string fecha_registro { get; set; }
    
        public virtual Proveedor proveedor { get; set; }
    }
}
