//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.producto = new HashSet<Producto>();
        }
    
        public int id { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Ingrese un teléfono válido")]
        [Display(Name = "Teléfono")]
        public Nullable<int> telefono { get; set; }

        public string fecha_registro { get; set; }
    
        public virtual ICollection<Producto> producto { get; set; }
    }
}
