//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required]
        [Display(Name = "Clave")]
        public string clave { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Seleccione tipo de usuario")]
        [Display(Name = "Tipo de usuario")]
        public Nullable<int> id_tipo { get; set; }

        public string fecha_registro { get; set; }
    
        public virtual TipoUsuario tipo { get; set; }
    }
}
